# Generated by Django 3.0 on 2020-04-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('camera', models.CharField(blank=True, max_length=250, null=True, verbose_name='camera')),
                ('size', models.FloatField(default=0.0, verbose_name='size')),
                ('creation_date', models.DateTimeField(blank=True, null=True, verbose_name='image created')),
                ('upload_date', models.DateTimeField(auto_now=True, null=True, verbose_name='image uploaded')),
                ('url', models.CharField(max_length=850, verbose_name='url')),
                ('thumb_url', models.CharField(max_length=850, verbose_name='thumbnail')),
            ],
        ),
    ]
