# Generated by Django 3.0 on 2020-04-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_img_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'get_latest_by': 'upload_date', 'ordering': ['-creation_date']},
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['img_hash'], name='gallery_ima_img_has_5b5908_idx'),
        ),
    ]
